version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - sam build
      - sam package --s3-bucket lambda-nodejs-artifacts --output-template-file outputTemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputTemplate.yml
